package com.cpen491.remote_mobility_monitoring.datastore.dao;

import com.cpen491.remote_mobility_monitoring.datastore.exception.DuplicateRecordException;
import com.cpen491.remote_mobility_monitoring.datastore.exception.RecordDoesNotExistException;
import com.cpen491.remote_mobility_monitoring.datastore.model.Caregiver;
import com.cpen491.remote_mobility_monitoring.datastore.model.Organization;
import com.cpen491.remote_mobility_monitoring.datastore.model.Patient;
import com.cpen491.remote_mobility_monitoring.dependency.utility.Validator;
import lombok.AllArgsConstructor;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.services.dynamodb.model.GetItemResponse;
import software.amazon.awssdk.services.dynamodb.model.QueryResponse;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import static com.cpen491.remote_mobility_monitoring.datastore.model.Const.CaregiverTable;
import static com.cpen491.remote_mobility_monitoring.datastore.model.Const.OrganizationTable;
import static com.cpen491.remote_mobility_monitoring.datastore.model.Const.PatientTable;

@Slf4j
@AllArgsConstructor
public class CaregiverDao {
    @NonNull
    GenericDao genericDao;
    @NonNull
    OrganizationDao organizationDao;
    @NonNull
    PatientDao patientDao;

    /**
     * Creates a new Caregiver record and adds it to an organization. Record with the given email must not already exist.
     *
     * @param newRecord The Caregiver record to create
     * @param organizationId The id of the Organization record
     * @throws RecordDoesNotExistException If Organization record with given organizationId does not exist
     * @throws DuplicateRecordException If record with the given email already exists
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if any of email, firstName, lastName,
     *                              title, phoneNumber, or organizationId are empty
     */
    public void create(Caregiver newRecord, String organizationId) {
        log.info("Creating new Caregiver record {}", newRecord);
        Validator.validateCaregiver(newRecord);
        Validator.validateOrganizationId(organizationId);

        Organization organization = organizationDao.findById(organizationId);

        if (findByEmail(newRecord.getEmail()) != null) {
            log.error("Caregiver record with email [{}] already exists", newRecord.getEmail());
            throw new DuplicateRecordException(Caregiver.class.getSimpleName(), newRecord.getEmail());
        }

        genericDao.setAutoGeneratedAttributes(newRecord, CaregiverTable.ID_PREFIX);
        Map<String, AttributeValue> caregiverMap = Caregiver.convertToMap(newRecord);
        genericDao.put(caregiverMap);
        genericDao.addAssociation(Organization.convertToMap(organization), caregiverMap);
    }

    /**
     * Checks whether Caregiver has Patient.
     *
     * @param patientId The id of the Patient record
     * @param caregiverId The id of the Caregiver record
     * @return {@link Boolean}
     * @throws RecordDoesNotExistException If Patient or Caregiver records do not exist
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if patientId or caregiverId is empty or invalid
     */
    public boolean hasPatient(String patientId, String caregiverId) {
        log.info("Checking that Caregiver [{}] has Patient [{}]", caregiverId, patientId);
        Validator.validatePatientId(patientId);
        Validator.validateCaregiverId(caregiverId);

        patientDao.findById(patientId);
        findById(caregiverId);

        GetItemResponse response = genericDao.findByPrimaryKey(caregiverId, patientId);
        return response.hasItem();
    }

    /**
     * Adds a Patient to a Caregiver. Patient and Caregiver must already exist.
     *
     * @param patientId The id of the Patient record
     * @param caregiverId The id of the Caregiver record
     * @throws RecordDoesNotExistException If Patient or Caregiver records do not exist
     * @throws DuplicateRecordException If Patient/Caregiver association already exists
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if patientId or caregiverId is empty or invalid
     */
    public void addPatient(String patientId, String caregiverId) {
        log.info("Adding Patient [{}] to Caregiver [{}]", patientId, caregiverId);
        Validator.validatePatientId(patientId);
        Validator.validateCaregiverId(caregiverId);

        Patient patient = patientDao.findById(patientId);
        Caregiver caregiver = findById(caregiverId);

        GetItemResponse response = genericDao.findByPrimaryKey(caregiverId, patientId);
        if (response.hasItem()) {
            log.error("Patient [{}] already associated with Caregiver [{}]", patientId, caregiverId);
            throw new DuplicateRecordException("Patient/Caregiver association", patientId + ":" + caregiverId);
        }

        genericDao.addAssociation(Caregiver.convertToMap(caregiver), Patient.convertToMap(patient));
    }

    /**
     * Removes a Patient from a Caregiver. Patient and Caregiver must already exist.
     *
     * @param patientId The id of the Patient record
     * @param caregiverId The id of the Caregiver record
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if patientId or caregiverId is empty or invalid
     */
    public void removePatient(String patientId, String caregiverId) {
        log.info("Removing Patient [{}] from Caregiver [{}]", patientId, caregiverId);
        Validator.validatePatientId(patientId);
        Validator.validateCaregiverId(caregiverId);

        genericDao.deleteByPrimaryKey(caregiverId, patientId);
    }

    /**
     * Finds a Caregiver record by id.
     *
     * @param id The id of the record to find
     * @return {@link Caregiver}
     * @throws RecordDoesNotExistException If record with the given id does not exist
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if id is empty or invalid
     */
    public Caregiver findById(String id) {
        log.info("Finding Caregiver record with id [{}]", id);
        Validator.validateCaregiverId(id);

        GetItemResponse response = genericDao.findByPartitionKey(id);
        if (!response.hasItem()) {
            log.error("Cannot find Caregiver record with id [{}]", id);
            throw new RecordDoesNotExistException(Caregiver.class.getSimpleName(), id);
        }
        return Caregiver.convertFromMap(response.item());
    }

    /**
     * Finds a Caregiver record by email. Returns null if record does not exist.
     *
     * @param email The email of the record to find
     * @return {@link Caregiver}
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if email is empty
     */
    public Caregiver findByEmail(String email) {
        log.info("Finding Caregiver record with email [{}]", email);
        Validator.validateEmail(email);

        QueryResponse response = genericDao
                .findAllByPartitionKeyOnIndex(CaregiverTable.EMAIL_NAME, email, CaregiverTable.EMAIL_INDEX_NAME);
        if (!response.hasItems() || response.items().size() == 0) {
            log.info("Cannot find Caregiver record with email [{}]", email);
            return null;
        }
        Caregiver caregiver = Caregiver.convertFromMap(response.items().get(0));
        genericDao.setCorrectId(caregiver, CaregiverTable.ID_PREFIX);
        return caregiver;
    }

    /**
     * Batch finds all Caregiver records by IDs.
     *
     * @param ids Set of IDs of the records to find
     * @return {@link List}
     * @throws NullPointerException If ids is null
     */
    public List<Caregiver> batchFindById(List<String> ids) {
        log.info("Batch finding caregiver records matching IDs {}", ids);
        Validator.validateIds(ids);
        for (String id : ids) {
            Validator.validateCaregiverId(id);
        }

        List<Map<String, AttributeValue>> result = genericDao.batchFindByPartitionKey(ids);
        return result.stream().map(Caregiver::convertFromMap).collect(Collectors.toList());
    }

    /**
     * Find the Organization this Caregiver belongs to.
     *
     * @param caregiverId The id of the Caregiver record
     * @return {@link Organization}
     * @throws RecordDoesNotExistException If record with the given caregiverId does not exist
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if caregiverId is empty or invalid
     */
    public Organization findOrganization(String caregiverId) {
        log.info("Finding Organization of Caregiver [{}]", caregiverId);
        Validator.validateCaregiverId(caregiverId);

        findById(caregiverId);

        QueryResponse response = genericDao
                .findAllAssociationsOnSidIndex(caregiverId, OrganizationTable.ID_PREFIX);
        if (!response.hasItems() || response.items().size() == 0) {
            log.info("Cannot find Organization of Caregiver [{}]", caregiverId);
            return null;
        }
        Organization organization = Organization.convertFromMap(response.items().get(0));
        organization.setSid(organization.getPid());
        return organization;
    }

    /**
     * Find all Patients of this Caregiver.
     *
     * @param caregiverId The id of the Caregiver record
     * @return {@link List}
     * @throws RecordDoesNotExistException If record with the given caregiverId does not exist
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if caregiverId is empty or invalid
     */
    public List<Patient> findAllPatients(String caregiverId) {
        log.info("Finding all Patient records of Caregiver [{}]", caregiverId);
        Validator.validateCaregiverId(caregiverId);

        findById(caregiverId);

        List<Map<String, AttributeValue>> result = genericDao
                .findAllAssociations(caregiverId, PatientTable.ID_PREFIX).items();
        return result.stream().map(map -> {
            Patient patient = Patient.convertFromMap(map);
            patient.setPid(patient.getSid());
            return patient;
        }).collect(Collectors.toList());
    }

    /**
     * Updates a Caregiver record. Record with given id must already exist.
     * Record with given email should not already exist unless it is the same record being updated.
     *
     * @param updatedRecord The Caregiver record to update
     * @throws DuplicateRecordException If record with the given email already exists
     * @throws RecordDoesNotExistException If record with the given id does not exist
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if any of pid, sid, email, firstName, lastName,
     *                              title, or phoneNumber are empty
     */
    public void update(Caregiver updatedRecord) {
        log.info("Updating Caregiver record {}", updatedRecord);
        Validator.validateCaregiver(updatedRecord);
        Validator.validatePidEqualsSid(updatedRecord.getPid(), updatedRecord.getSid());
        Validator.validateCaregiverId(updatedRecord.getPid());

        Caregiver found = findByEmail(updatedRecord.getEmail());
        if (found != null && !found.getPid().equals(updatedRecord.getPid())) {
            log.error("Caregiver record with email [{}] already exists", updatedRecord.getEmail());
            throw new DuplicateRecordException(Caregiver.class.getSimpleName(), updatedRecord.getEmail());
        }

        findById(updatedRecord.getPid());

        genericDao.update(Caregiver.convertToMap(updatedRecord));
    }

    /**
     * Deletes a Caregiver record by id and all of its associations. Does nothing if record does not exist.
     *
     * @param id The id of the record to delete
     * @throws IllegalArgumentException
     * @throws NullPointerException Above 2 exceptions are thrown if id is empty or invalid
     */
    public void delete(String id) {
        log.info("Deleting Caregiver record with id [{}]", id);
        Validator.validateCaregiverId(id);

        genericDao.delete(id);
    }
}
